// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Client struct {
	ID        string
	Name      string
	Email     string
	Phone     sql.NullString
	Address   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	AgentID   string
}

type RefreshToken struct {
	Token     string
	CreatedAt string
	UpdatedAt string
	UserID    string
	ExpiresAt string
	RevokedAt sql.NullString
}

type Thread struct {
	ID        int64
	ThreadID  string
	ContactID string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	UserID    string
}

type User struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
	AvatarUrl    sql.NullString
	IsAdmin      sql.NullBool
	AvatarID     string
}

type VideoSeries struct {
	ID          string
	Title       string
	Description sql.NullString
	UserID      string
	ClientID    string
	S3Url       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type VideoTemplate struct {
	ID          string
	Title       string
	Description sql.NullString
	UserID      string
	S3Url       sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type VoiceAssistant struct {
	ID             int64
	Name           string
	ClonedVoiceID  string
	TotalCallsMade sql.NullInt64
	TotalDuration  sql.NullInt64
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	UserID         string
}
