// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: test.sql

package database

import (
	"context"
)

const testQuery = `-- name: TestQuery :one
SELECT 1
`

func (q *Queries) TestQuery(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, testQuery)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
