// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: threads.sql

package database

import (
	"context"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (user_id, contact_id, thread_id)
VALUES (
    ?,
    ?,
    ?
) RETURNING id, thread_id, contact_id, created_at, updated_at, user_id
`

type CreateThreadParams struct {
	UserID    string
	ContactID string
	ThreadID  string
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, createThread, arg.UserID, arg.ContactID, arg.ThreadID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ContactID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, thread_id, contact_id, created_at, updated_at, user_id FROM threads WHERE user_id = ? AND contact_id = ?
`

type GetThreadParams struct {
	UserID    string
	ContactID string
}

func (q *Queries) GetThread(ctx context.Context, arg GetThreadParams) (Thread, error) {
	row := q.db.QueryRowContext(ctx, getThread, arg.UserID, arg.ContactID)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.ContactID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
