// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, username, email, password_hash, created_at, updated_at)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
RETURNING id, username, email, password_hash, created_at, updated_at, avatar_url, is_admin, avatar_id
`

type CreateUserParams struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.AvatarID,
	)
	return i, err
}

const getUserAvatarId = `-- name: GetUserAvatarId :one
SELECT id, username, email, password_hash, created_at, updated_at, avatar_url, is_admin, avatar_id FROM users WHERE avatar_id = ?
`

func (q *Queries) GetUserAvatarId(ctx context.Context, avatarID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserAvatarId, avatarID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.AvatarID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, created_at, updated_at, avatar_url, is_admin, avatar_id FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.AvatarID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, created_at, updated_at, avatar_url, is_admin, avatar_id FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.AvatarID,
	)
	return i, err
}

const updateUserAvatarId = `-- name: UpdateUserAvatarId :one
UPDATE users SET avatar_id = ? WHERE id = ?
RETURNING id, username, email, password_hash, created_at, updated_at, avatar_url, is_admin, avatar_id
`

type UpdateUserAvatarIdParams struct {
	AvatarID string
	ID       string
}

func (q *Queries) UpdateUserAvatarId(ctx context.Context, arg UpdateUserAvatarIdParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserAvatarId, arg.AvatarID, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AvatarUrl,
		&i.IsAdmin,
		&i.AvatarID,
	)
	return i, err
}
