// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: video_avatars.sql

package database

import (
	"context"
	"database/sql"
)

const createAvatar = `-- name: CreateAvatar :one
INSERT INTO video_avatars(id, template_type, avatar_id, title, description, user_id)
VALUES(
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)RETURNING id, template_type, avatar_id, title, description, user_id, s3_url, created_at, updated_at
`

type CreateAvatarParams struct {
	ID           string
	TemplateType string
	AvatarID     string
	Title        string
	Description  sql.NullString
	UserID       string
}

func (q *Queries) CreateAvatar(ctx context.Context, arg CreateAvatarParams) (VideoAvatar, error) {
	row := q.db.QueryRowContext(ctx, createAvatar,
		arg.ID,
		arg.TemplateType,
		arg.AvatarID,
		arg.Title,
		arg.Description,
		arg.UserID,
	)
	var i VideoAvatar
	err := row.Scan(
		&i.ID,
		&i.TemplateType,
		&i.AvatarID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvatarById = `-- name: GetAvatarById :one
SELECT id, template_type, avatar_id, title, description, user_id, s3_url, created_at, updated_at FROM video_avatars WHERE id = ?
`

func (q *Queries) GetAvatarById(ctx context.Context, id string) (VideoAvatar, error) {
	row := q.db.QueryRowContext(ctx, getAvatarById, id)
	var i VideoAvatar
	err := row.Scan(
		&i.ID,
		&i.TemplateType,
		&i.AvatarID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAvatarsByUser = `-- name: GetAvatarsByUser :many
SELECT id, template_type, avatar_id, title, description, user_id, s3_url, created_at, updated_at FROM video_avatars WHERE user_id = ?
`

func (q *Queries) GetAvatarsByUser(ctx context.Context, userID string) ([]VideoAvatar, error) {
	rows, err := q.db.QueryContext(ctx, getAvatarsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoAvatar
	for rows.Next() {
		var i VideoAvatar
		if err := rows.Scan(
			&i.ID,
			&i.TemplateType,
			&i.AvatarID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.S3Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvatarsByUserAndTemplateType = `-- name: GetAvatarsByUserAndTemplateType :many
SELECT id, template_type, avatar_id, title, description, user_id, s3_url, created_at, updated_at FROM video_avatars WHERE user_id = ? AND template_type = ""
`

func (q *Queries) GetAvatarsByUserAndTemplateType(ctx context.Context, userID string) ([]VideoAvatar, error) {
	rows, err := q.db.QueryContext(ctx, getAvatarsByUserAndTemplateType, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoAvatar
	for rows.Next() {
		var i VideoAvatar
		if err := rows.Scan(
			&i.ID,
			&i.TemplateType,
			&i.AvatarID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.S3Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideoAvatar = `-- name: UpdateVideoAvatar :exec
UPDATE video_avatars
SET s3_url = ?
WHERE id = ?
`

type UpdateVideoAvatarParams struct {
	S3Url sql.NullString
	ID    string
}

func (q *Queries) UpdateVideoAvatar(ctx context.Context, arg UpdateVideoAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoAvatar, arg.S3Url, arg.ID)
	return err
}
