// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: videos.sql

package database

import (
	"context"
	"database/sql"
)

const createVideoMeta = `-- name: CreateVideoMeta :one
INSERT INTO video_templates (id, user_id, title, description )
VALUES(
    ?,
    ?,
    ?,
    ?
)RETURNING id, title, description, user_id, s3_url, created_at, updated_at
`

type CreateVideoMetaParams struct {
	ID          string
	UserID      string
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateVideoMeta(ctx context.Context, arg CreateVideoMetaParams) (VideoTemplate, error) {
	row := q.db.QueryRowContext(ctx, createVideoMeta,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i VideoTemplate
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoById = `-- name: GetVideoById :one
SELECT id, title, description, user_id, s3_url, created_at, updated_at FROM video_templates WHERE id = ?
`

func (q *Queries) GetVideoById(ctx context.Context, id string) (VideoTemplate, error) {
	row := q.db.QueryRowContext(ctx, getVideoById, id)
	var i VideoTemplate
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideosByUser = `-- name: GetVideosByUser :many
SELECT id, title, description, user_id, s3_url, created_at, updated_at FROM video_templates WHERE user_id = ?
`

func (q *Queries) GetVideosByUser(ctx context.Context, userID string) ([]VideoTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getVideosByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoTemplate
	for rows.Next() {
		var i VideoTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.S3Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVideo = `-- name: UpdateVideo :exec
UPDATE video_templates 
SET
    title = ?,
    description = ?,
    user_id = ?,
    s3_url = ?
WHERE id = ?
`

type UpdateVideoParams struct {
	Title       string
	Description sql.NullString
	UserID      string
	S3Url       sql.NullString
	ID          string
}

func (q *Queries) UpdateVideo(ctx context.Context, arg UpdateVideoParams) error {
	_, err := q.db.ExecContext(ctx, updateVideo,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.S3Url,
		arg.ID,
	)
	return err
}
