// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: video_series.sql

package database

import (
	"context"
	"database/sql"
)

const createVideoSeriesMeta = `-- name: CreateVideoSeriesMeta :one
INSERT INTO video_series (id, user_id, title, description )
VALUES(
    ?,
    ?,
    ?,
    ?
)RETURNING id, title, description, user_id, s3_url, audio_s3, created_at, updated_at
`

type CreateVideoSeriesMetaParams struct {
	ID          string
	UserID      string
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateVideoSeriesMeta(ctx context.Context, arg CreateVideoSeriesMetaParams) (VideoSeries, error) {
	row := q.db.QueryRowContext(ctx, createVideoSeriesMeta,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
	)
	var i VideoSeries
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.AudioS3,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideoSeriesById = `-- name: GetVideoSeriesById :one
SELECT id, title, description, user_id, s3_url, audio_s3, created_at, updated_at FROM video_series WHERE id = ?
`

func (q *Queries) GetVideoSeriesById(ctx context.Context, id string) (VideoSeries, error) {
	row := q.db.QueryRowContext(ctx, getVideoSeriesById, id)
	var i VideoSeries
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.AudioS3,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVideosSeriesByUserAndClient = `-- name: GetVideosSeriesByUserAndClient :many
SELECT id, title, description, user_id, s3_url, created_at, updated_at FROM video_templates WHERE user_id = ?
`

func (q *Queries) GetVideosSeriesByUserAndClient(ctx context.Context, userID string) ([]VideoTemplate, error) {
	rows, err := q.db.QueryContext(ctx, getVideosSeriesByUserAndClient, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoTemplate
	for rows.Next() {
		var i VideoTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.S3Url,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAudioUrl = `-- name: SetAudioUrl :one
UPDATE video_series SET audio_s3 = ?
WHERE id = ?
RETURNING id, title, description, user_id, s3_url, audio_s3, created_at, updated_at
`

type SetAudioUrlParams struct {
	AudioS3 string
	ID      string
}

func (q *Queries) SetAudioUrl(ctx context.Context, arg SetAudioUrlParams) (VideoSeries, error) {
	row := q.db.QueryRowContext(ctx, setAudioUrl, arg.AudioS3, arg.ID)
	var i VideoSeries
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.S3Url,
		&i.AudioS3,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVideoSeries = `-- name: UpdateVideoSeries :exec
UPDATE video_series 
SET
    title = ?,
    description = ?,
    user_id = ?,
    s3_url = ?
WHERE id = ?
`

type UpdateVideoSeriesParams struct {
	Title       string
	Description sql.NullString
	UserID      string
	S3Url       sql.NullString
	ID          string
}

func (q *Queries) UpdateVideoSeries(ctx context.Context, arg UpdateVideoSeriesParams) error {
	_, err := q.db.ExecContext(ctx, updateVideoSeries,
		arg.Title,
		arg.Description,
		arg.UserID,
		arg.S3Url,
		arg.ID,
	)
	return err
}
