// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: voice_assistants.sql

package database

import (
	"context"
)

const createVoiceAssistant = `-- name: CreateVoiceAssistant :one
INSERT INTO voice_assistants (name, cloned_voice_id, user_id)
VALUES (
    ?,
    ?,
    ?
)
RETURNING id, name, cloned_voice_id, total_calls_made, total_duration, created_at, updated_at, user_id
`

type CreateVoiceAssistantParams struct {
	Name          string
	ClonedVoiceID string
	UserID        string
}

func (q *Queries) CreateVoiceAssistant(ctx context.Context, arg CreateVoiceAssistantParams) (VoiceAssistant, error) {
	row := q.db.QueryRowContext(ctx, createVoiceAssistant, arg.Name, arg.ClonedVoiceID, arg.UserID)
	var i VoiceAssistant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClonedVoiceID,
		&i.TotalCallsMade,
		&i.TotalDuration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getAssistantsByUserID = `-- name: GetAssistantsByUserID :many
SELECT id, name, cloned_voice_id, total_calls_made, total_duration, created_at, updated_at, user_id FROM voice_assistants WHERE user_id = ?
`

func (q *Queries) GetAssistantsByUserID(ctx context.Context, userID string) ([]VoiceAssistant, error) {
	rows, err := q.db.QueryContext(ctx, getAssistantsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoiceAssistant
	for rows.Next() {
		var i VoiceAssistant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClonedVoiceID,
			&i.TotalCallsMade,
			&i.TotalDuration,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
